---
version: "2"
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: "![](toolchain.svg?localize)"
  icon: secure-lock-kubernetes.svg
  required:
    - build
  $configuration:
     ENABLE_EXTENSIONS: true
     ENABLE_IF_ELSE: true
     EXPRESSION_MAXLENGTH: 1000
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: "ibp-mustgather-{{timestamp}}"
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted"
services:
  build:
    service_id: pipeline
    parameters:
      name: 'ci-pipeline'
      ui-pipeline: true
      type: 'classic'
      configuration:
        content:
          $ref: pipeline.yml
          $refType: text
        env:
          APP_NAME: "{{form.pipeline.parameters.app-name}}"
          REGISTRY_REGION_ID: "{{form.pipeline.parameters.registry-region}}"
          REGISTRY_NAMESPACE: "{{form.pipeline.parameters.registry-namespace}}"
          API_KEY: "{{form.pipeline.parameters.api-key}}"
          PROD_REGION_ID: "{{form.pipeline.parameters.prod-region}}"
          PROD_RESOURCE_GROUP: "{{form.pipeline.parameters.prod-resource-group}}"
          PROD_CLUSTER_NAME: "{{form.pipeline.parameters.prod-cluster-name}}"
          PROD_CLUSTER_NAMESPACE: "{{form.pipeline.parameters.prod-cluster-namespace}}"
        execute: true
form:
  pipeline:
    parameters:
      app-name: "ibp-mustgather"
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
